---
title: "Seedlings"
output: pdf_document
classoption: a4paper
geometry: margin=1.8cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages
library("tidyverse")

seed <- read_csv2("~/OneDrive - University of Bergen/Research/FunCaB/Data/primary/veg_recruitment/2018_funcab_seedlings.csv")

speciesID <- seed %>% gather(key = "species", value = "presence", unID:NS) %>% filter(!is.na(presence)) %>% distinct(turfID, seedID, species)

seed <- seed %>% 
  filter(Treatment %in% c("C", "FGB", "G", "B", "GB")) %>% 
  select(turfID, seedID, x, y, survival) %>% 
  left_join(speciesID) %>% 
  filter(!species == "NS") %>% 
  mutate(newSurv = "") %>% 
  arrange(x,y)
  

```

# seedling maps
```{r, fig.height=5.5, fig.width = 5.5, results='asis'}
plyr::d_ply(seed, plyr::.(turfID), function(df){
  print(
  ggplot(df, aes(x = x, y = y, label = seedID)) +
  geom_point() +
  facet_wrap(~ turfID) +
  geom_text(nudge_x = -7, nudge_y = 7) +
  theme_bw() +
  scale_x_continuous(limits = c(0, 250), breaks = c(0, 50, 100, 150, 200, 250)) +
  scale_y_continuous(limits = c(0, 250), breaks = c(0, 50, 100, 150, 200, 250))
  )
  print(
    if(nrow(df) > 28) {
      n1 <- ceiling(nrow(df) / 2)
      df1 <- df[1:n1, 2:7]
      df2 <- df[-(1:n1), 2:7]
        if (nrow(df) %% 2 == 1) {
      #odd nrow - pad df2
          df2 <- df2 %>% add_row()
      }
      bind_cols(df1, df2) %>% knitr::kable(format = "pandoc")
      } else{
      knitr::kable(df[, 2:7], format = "latex")
      }
      )
cat("\n\n\\pagebreak\n")
}
      )
```
